environment: dev

gems:
  - bourbon
  - neat
  - jekyll-sitemap

# Structure configuration
source: source
destination: build

assets:
  dirname: assets
  baseurl: /assets/
  cachebust: soft
  source:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  debug: true

# Site settings
title: You're the Worst
description: Just some things Myles Braithwaite thinks are the worst.
keywords:
  - Myles Braithwaite
  - Worst
  - You're the Worst
permalink: /:year-:month-:day/

# Author information
author: Myles Braithwaite
email: myles@youaretheworst.today
twitter_username: mylesb

# URL settings
baseurl: ""
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown
