environment: dev

gems:
  - bourbon
  - neat
  - jekyll-sitemap
  - jekyll_pages_api_search

# Structure configuration
source: source
destination: build

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _gifs
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  debug: true

jekyll_pages_api_search:
  index_fields:
    body:
      boost: 10

# Site settings
title: "You're the Worst"
description: Just some things Myles Braithwaite thinks are the worst.
keywords:
  - Myles Braithwaite
  - Worst
  - The Worst
  - "You're the Worst"
permalink: /:year-:month-:day/

# Author information
author: Myles Braithwaite
email: myles@youaretheworst.today
twitter_username: mylesb

# URL settings
baseurl: ""
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown

prose:
  rooturl: 'source/_posts'
  siteurl: 'https://youaretheworst.today/'
  relativeLinks: 'https://youaretheworst.today/links.josnp'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "hidden"
          value: "theworst"
